### ISSUE TITLE
Wrong python interpreter despite specifying correct path for executable

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITKExamples#106]
I am working in a python3 venv and attempting to configure Cmake to build documentation for ITK Examples. During configuration, I set the `python_executable` to the path of the virtual environment. When configured, I get the following message:

`CMake Error at src/CMakeLists.txt:29 (message):` 
`Building the documentation requires Python >= 2.7`

The Python version is up to date and when the Python Interpreter is accessed in CMakeLists.txt, the correct path to the virtual environment is given.
@hjmjohnson

**Comment by thewtex** [comment]
@mseng10 the values of the `PYTHON_EXECUTABLE` setting can be checked in the *CMakeCache.txt* file of the build directory -- does this have the correct value?

**Comment by mseng10** [comment]
@thewtex Yes, the value is correct.

**Comment by mseng10** [comment]
Error fixed with recent merge. Closing Issue.
