### ISSUE TITLE
Conform to C++ style guidelines

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKExamples#116]
It looks like the C++ examples that were recently ported from the `WikiExamples` (PRs #109 and #112) do not conform to the C++ style (flow control statement bracket indentation, two white space indentation for code, etc.), e.g.
[CreateGaussianKernel](https://github.com/InsightSoftwareConsortium/ITKExamples/blob/master/src/Core/Common/CreateGaussianKernel/Code.cxx)
or
[ResamleDICOMSeries](https://github.com/InsightSoftwareConsortium/ITKExamples/blob/master/src/IO/GDCM/ResamleDICOMSeries/Code.cxx)

The files were either not checked by the KWStyle checker when being committed, the editor was configured to conform to Python indentation (four white spaces) or some other issue happened.

C++ source files should have two white space indentation, and conform to the KWStyle checker which implements (some of) the [ITK SW Guide](https://itk.org/ItkSoftwareGuide.pdf) style rules (Appendix C).

**Comment by jhlegarreta** [comment]
@mseng10 @hjmjohnson the effort was huge, so thanks. This will be hopefully fixed at some point.

**Comment by thewtex** [comment]
Is this all set? The linter GitHub Action is green.

#224 adds a clang-format pre-commit hook for C++.

Perhaps we should also add a `black` pre-commit hook for Python code? And in the *ITK* repository?

**Comment by jhlegarreta** [comment]
PR #112 changes are too many to check, but the one in #109 has not changed.

Maybe the linter GitHub Action only acts on modified code, not the whole repository, and I guess that will be the case for the clang-format pre-commit hook, which are both very nice :100: additions.

I'm afraid these files will need a manual check/edition.

Yes, I fully agree that adding a `black` pre-commit hook both for the examples and ITK would be another great addition towards style consistency and automation :100:.

**Comment by thewtex** [comment]
@jhlegarreta I went through and ran clang-format on all C++ sources, and we are in good shape! :tophat: 

#230 adds Python style pre-commit hook / linting.

**Comment by jhlegarreta** [comment]
Wonderful Matt. Thanks.
