### ISSUE TITLE
Configure module to adhere to new GitHub Actions

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITKExamples#159]
This issue contains the actions needed for this module in relation to it's parent issue [here](https://github.com/InsightSoftwareConsortium/ITK/issues/1828). This will require the following changes:

- [x] Remove Azure Pipeline testing and update README
- [x] Import GitHub Actions configuration files and implement them into ITKExamples. Also, update the README with the GitHub Actions badge.
- [x] Make PR.
- [x] Make all CXX builds pass
- [x] Make all Python builds pass
- [x] Make Sphinx Documentation build 
- [ ] Deploy documentation to website with Netlify

**NOTE:** When configuring this module to adhere to the new GitHub Actions, there are a few differences between this module and the ITKModuleTemplate. These are stated below.

1. No `setup.py` script
2. No PyPI package for ITKExamples

@hjmjohnson @thewtex For this module, I am confused as to the required GitHub Actions needed. Are we taking special actions for this module? If so, can either of you help direct me to the actions needed? Any help would be greatly appreciated.

**Comment by thewtex** [comment]
@mseng10 thanks for taking this on :pray: 

Cross-platform builds for the examples is a good way to get started.

After the build are working, good next steps are to add documentation builds (bring in #97).

Then, add also a website deploy preview, e.g. with Netlify.

  https://github.com/netlify/actions
