### ISSUE TITLE
Link broken for ConvertAnITKGrayScaleImageToCVMat example

### ISSUE THREAD

**Issue by arnaudgelas** [InsightSoftwareConsortium/ITKExamples#16]
http://public.kitware.com/pub/itk/Examples/src/Video/BridgeOpenCV/ConvertAnITKGrayScaleImageToCVMat/ConvertAnITKGrayScaleImageToCVMat.zip

**Comment by thewtex** [comment]
The dashboard build that generates the output now builds with `ITKExamples_USE_OpenCV:BOOL=ON`, and the file is available.
