### ISSUE TITLE
New warnings generated from recent documentation changes

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITKExamples#165]
I am trying to complete #160 and I have all builds passing except for the Documentation build. Currently there are roughly 200 compiler warnings being generated from the recent changes. I have fixed most of them except for the following 2:

1. `WARNING: Duplicate declaration` - This warning is being called when the `..breathelink` attempts to link a class. This has no affect on its functionality, but I am unable to get a clean build to pass.
2. `WARNING: doxygenclass: Cannot find class` - This is the more concerning warning as the `..breathelink` cannot find the class in the Doxygen xml. Because of this, we cannot implement proper links in our documentation for certain classes.

I am unsure of how to handle these 2 warnings, so any help would be greatly appreciated. Below is a link to a recent cdash build with more information on the warnings.

https://open.cdash.org/viewBuildError.php?type=1&buildid=6617423

**Comment by jhlegarreta** [comment]
@mseng10 thanks for this effort !

As for the first issue, maybe you already had a look at [this](https://github.com/sphinx-doc/sphinx/issues/4820), but mentioning it just in case. There are a few issues/PRs cross-referenced, and it may not be straightforward to find the fix through them, but may be worthwhile having a look.

As for the second one, maybe this and the linked and merged PR give some clue: https://github.com/PCMSolver/pcmsolver/issues/100 ?

I must confess that I am not familiar with the issues, and that I have not had a closer look.

**Comment by mseng10** [comment]
Fixed in #185
