### ISSUE TITLE
Nightly documentation updates failing

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKExamples#201]
# Overview
The documentation at [https://itk.org/ITKExamples/](https://itk.org/ITKExamples/) is listed as being last updated on November 27, 2020 and does not reflect recent example updates and fixes.

## Expected behavior
[Public documentation](https://itk.org/ITKExamples/) is built and deployed nightly.

## Observed behavior
Build issue with `git-lfs`:
> git-lfs filter-process: 1: git-lfs filter-process: git-lfs: not found
fatal: The remote end hung up unexpectedly
Unable to checkout '16c4dde2ee2a19a0278473fed03c852482006a6e' in submodule path 'ThirdParty/vtkm/vtk-m'
CMake Error at VTK-prefixVTK-gitclone.cmake:49 (message):
  Failed to update submodules in:
  '/home/kitware/Dashboards/Tests/ITKExamples-doc-build/VTK'

See full error report at [https://open.cdash.org/viewBuildError.php?buildid=7060740](https://open.cdash.org/viewBuildError.php?buildid=7060740).

### Notes
@thewtex has installed `git-lfs` on the build server to address the issue, updated results are pending.

**Comment by thewtex** [comment]
Checking the build system, it did not have the required `six` package. #202 attempts to resolve this.

**Comment by tbirdso** [comment]
[Dashboard](https://open.cdash.org/build/7065262) shows 1 build error:
> Could not find a version that satisfies the requirement itk>=5.2rc2 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 4.13.2, 4.13.2.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.1b1, 5.1rc1.post1, 5.1rc2, 5.1rc3, 5.1.0, 5.1.0.post1, 5.1.0.post2, 5.1.0.post3, 5.1.1, 5.1.1.post1, 5.1.2)
No matching distribution found for itk\>=5.2rc2

**Comment by jhlegarreta** [comment]
`itk 5.2.rc2` is [still in pre-release](https://pypi.org/project/itk/#history). If these need to be tested, the `--pre` flag needs to be provided to `pip install`.

**Comment by tbirdso** [comment]
Thanks @jhlegarreta . I've added the flag in [PR 207](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/207).

**Comment by tbirdso** [comment]
Fixed in [PR 211](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/211). Public ITK Examples page shows successful nightly build:

> This is the v5.2.0 documentation, last updated Mar 01, 2021.
