### ISSUE TITLE
Invalid links to pictures in UploadBinaryData.rst

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKExamples#25]
The links to the pictures in [`UploadBinaryData.rst`](ITKExamples/Documentation/Contribute/UploadBinaryData.rst) are invalid. These pictures do not exist.

Do we intend to upload them, or we'd rather remove the links?

**Comment by thewtex** [comment]
@jhlegarreta Checking on this page, all links and pictures seem valid:

  https://itk.org/ITKExamples/Documentation/Contribute/UploadBinaryData.html

Can we close this issue?

**Comment by jhlegarreta** [comment]
Yes Matt. Everything looks OK. Closing the issue.
