### ISSUE TITLE
Re-enable Otsu baseline test after ITK 5.0b02 release

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKExamples#75]
This was disabled in #70 because of a difference in behavior between C++ and Python. Re-enable after the ITK 5.0 Beta 2 Python packages have been released.

**Comment by jhlegarreta** [comment]
ITK 5.0 Beta 2 was release a while ago, and releases have been rolled ever since to refine towards a more robust ITK 5.0 released. @thewtex should we re-enabled the Otsu baseline tests? If yes, I can submit a path set.
