### ISSUE TITLE
Point documentation to github resources

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITKExamples#94]
All repos listed at https://itk.org/gitweb should be syncronized with github, removed, or at least have a major banner message indicating that it is out of date.

Update sphinx documentation
```
-.. _ITKApps:               https://itk.org/ITKApps.git
+.. _ITKApps:               https://github.com/InsightSoftwareConsortium/ITKApps
```

**Comment by thewtex** [comment]
These are now all updated.
