### ISSUE TITLE
Update ITK Superbuild version to 5.0 RC 2

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKExamples#99]

**Comment by fbudin69500** [comment]
I was able to reproduce this issue with the PR #103 and also by installing ITK v5.0rc2 Python packages, but when I use the latest version of ITK built on my computer, the test passes. Hopefuily the issue that arises here has been independently addressed in ITK. We can wait until there is a new ITK Python package updated on Github to make sure that it is actually fixed.
